<!DOCTYPE html>
<html lang="en">

<head>
    <title> <?php echo $title ?> </title>
    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Favicon icon -->
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="/icon/themify-icons/themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="/icon/icofont/css/icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.mCustomScrollbar.css">

    <script type="text/javascript" src="/js/jquery/jquery.min.js"></script>

    <script type="text/javascript" src="/js/timezone/moment.min.js"></script>
    <script type="text/javascript" src="/js/timezone/moment-timezone.js"></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-fox9JsAWvfxE5PJJnjgYlYDwNJD9GUY" async defer></script>

    <script>
        var map = null;
        var markers = null;
        function initialize() {
            var centerLatLng = new google.maps.LatLng( 50, 50 );
            map = new google.maps.Map(document.getElementById('currentMap'), {
                zoom: 15,
                center: centerLatLng,
            });

            markers = new google.maps.Marker( {position: centerLatLng, map: map} );

            markers.setMap( map );
        }

        function moveMarker( lat, lon ) {
            if (markers == null || map == null)
                return;

            markers.setMap(null);

            markers = new google.maps.Marker( {position: new google.maps.LatLng(lat, lon), map: map} );

            markers.setPosition( new google.maps.LatLng( lat, lon ) );
            map.panTo( new google.maps.LatLng( lat, lon ) );
        };

    /*    var map;
        var markers = null;
        function initialize() {
            var centerLatLng = new google.maps.LatLng( 50, 50 );
            map = new google.maps.Map(document.getElementById('markermap'), {
                zoom: 4,
                center: centerLatLng,
                //mapTypeId: google.maps.MapTypeId.ROADMAP
            });

  //          markers = new google.maps.Marker( {position: centerLatLng, map: map} );

//            markers.setMap( map );
        }

        function moveMarker( lat, lon ) {
            markers.setMap(null);

            markers = new google.maps.Marker( {position: new google.maps.LatLng(lat, lon), map: map} );

//            markers.setPosition( new google.maps.LatLng( lat, lon ) );
///            map.panTo( new google.maps.LatLng( lat, lon ) );
        };

        function addMarker(lat, lon) {
            markers = null;

            var latlng = new google.maps.LatLng(lat, lon);
            markers = new google.maps.Marker({
                position: latlng,
                map: map
            });

            markers.setMap( map );
        } */
    </script>

    <style>
        .line {
            fill: none;
            stroke: #000;
            stroke-width: 1.5px;
        }

        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
 /*       .graph .axis {
            stroke-width: 1;
        }

        ,line {
             clip-path: url(#clip);
         }

        .graph .axis .tick line {
            stroke: black;
        }

        .graph .axis .tick text {
            fill: black;
            font-size: 0.7em;
        }

        .graph .axis .domain {
            fill: none;
            stroke: black;
        }

        .graph .group {
            fill: none;
            stroke: black;
            stroke-width: 1.5;
        } */
    </style>
</head>

<body>
<div id="pcoded" class="pcoded">
    <div class="pcoded-container navbar-wrapper">
        <nav class="navbar header-navbar pcoded-header">
            <div class="navbar-wrapper">

                <div class="navbar-logo">
                    <a class="mobile-menu" id="mobile-collapse" target="_self" style="color: #000000; cursor: pointer;">
                        <i class="ti-menu"></i>
                    </a>
                    <a href="/">
                        <img class="img-fluid" src="/img/logo/logo.png" width="120" height="30" alt="Theme-Logo"/>
                    </a>
                    <a class="mobile-options">
                        <i class="ti-more"></i>
                    </a>
                </div>

                <div class="navbar-container container-fluid">
                    <ul class="nav-right">
                        <li>
                            <form id="signout" action="/signout" method="post">
                                <input type="hidden" name="csrf-token" value="<?php echo $_SESSION['csrf-token'] ?>"/>
                            </form>

                            <a href="#" onclick="$('#signout').submit(); return false">
                                <i class="ti-layout-sidebar-left"></i> Signout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="pcoded-main-container">
            <div class="pcoded-wrapper">
                <nav class="pcoded-navbar">
                    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
                    <div class="pcoded-inner-navbar main-menu">
                        <div class="">
                            <div class="main-menu-header">
                                <div class="user-details">
                                    <span id="more-details"><?php echo $user['fname'] . ' ' . $user['lname'] ?><i
                                                class="ti-angle-down"></i></span>
                                </div>
                            </div>

                            <div class="main-menu-content">
                                <ul>
                                    <li class="more-details">
                                        <a href="/profile"><i class="ti-user"></i>Profile</a>
                                        <a href="/boards"><i class="ti-tablet"></i>Boards</a>
                                        <a href="#" onclick="$('#signout').submit(); return false">
                                            <i class="ti-layout-sidebar-left"></i>Signout
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="pcoded-navigatio-lavel">Home</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li class="active">
                                <a href="/">
                                    <span class="pcoded-micon"><i class="ti-home"></i></span>
                                    <span class="pcoded-mtext">Dashboard</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">Air Quality Index</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/aqimaps">
                                    <span class="pcoded-micon"><i class="ti-map-alt"></i></span>
                                    <span class="pcoded-mtext">Real-time AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>

                            <li>
                                <a href="/historyaqi">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Historical AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">User Air Pollution</div>
                        <?php if (count($boards) > 0) {
                            for ($i = 0; $i < count($boards); ++$i) { ?>
                                <ul class="pcoded-item pcoded-left-item">
                                    <li class="pcoded-hasmenu">
                                        <a href="javascript:void(0)">
                                            <span class="pcoded-micon"><i class="ti-tablet"></i></span>
                                            <span class="pcoded-mtext"><?php echo $boards[$i]['name'] ?></span>
                                            <span class="pcoded-mcaret"></span>
                                        </a>
                                        <ul class="pcoded-submenu">
                                            <li>
                                                <a href="/realtimeap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Real-Time Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/historyap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                                    <span class="pcoded-mtext">Historical Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/paqichart/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Historical AQI Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            <?php }
                        } else { ?>
                            <ul class="pcoded-item pcoded-left-item">
                                <li>
                                    <a>
                                        <span style="width: 30px; display: inline-block;"></span>
                                        <span class="pcoded-mtext">No Boards</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li>
                            </ul>
                        <?php } ?>

                        <div class="pcoded-navigatio-lavel">User Healthcare information</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/realtimehr">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Real-Time Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                            <li>
                                <a href="/historyhr">
                                    <span class="pcoded-micon"><i class="ti-archive"></i></span>
                                    <span class="pcoded-mtext">Historical Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="pcoded-content">
                    <div class="pcoded-inner-content">
                        <!-- Main-body start -->
                        <div class="main-body">
                            <div class="page-wrapper">
                                <!-- Page-header start -->
                                <div class="page-header card">
                                    <div class="row align-items-end">
                                        <div class="col-lg-8">
                                            <div class="page-header-title">
                                                <i class="icofont icofont-pulse bg-c-pink"></i>
                                                <div class="d-inline">
                                                    <h4>Real time Heart Rate</h4>
                                                    <span><?php echo $user['fname']?>'s real time heart rate charts</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="page-header-breadcrumb">
                                                <ul class="breadcrumb-title">
                                                    <li class="breadcrumb-item">
                                                        <a href="/">
                                                            <i class="icofont icofont-home"></i>
                                                        </a>
                                                    </li>
                                                    <li class="breadcrumb-item"><a href="/realtimehr">Real Time Heart Rate</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page-header end -->



                                <!-- Page body start -->
                                <div class="page-body">
                                    <div class="error-msg">
                                        <div class="row">
                                            <h4 style="margin: 0 auto; line-height: 400px">There is no connection with Sensor</h4>
                                        </div>
                                    </div>

                                    <div class="hr_chart" style="display: none">
                                        <div class="row">
                                            <div class="col-md-6 col-xl-3">
                                                <div class="card widget-card-1">
                                                    <div class="card-block-small">
                                                        <i class="icofont icofont-pulse bg-c-pink card1-icon"></i>
                                                        <span class="text-c-pink f-w-600">HR Current</span>
                                                        <div>
                                                        <h4 class="current_hr"></h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-6 col-xl-3">
                                                <div class="card widget-card-1">
                                                    <div class="card-block-small">
                                                        <i class="icofont icofont-pulse bg-c-green card1-icon"></i>
                                                        <span class="text-c-green f-w-600">RR Interval</span>
                                                        <div>
                                                            <h4 class="current_rr"></h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-6 col-xl-3">
                                                <div class="card widget-card-1">
                                                    <div class="card-block-small">
                                                        <i class="icofont icofont-time bg-c-blue card1-icon"></i>
                                                        <span class="text-c-blue f-w-600">Current Time</span>
                                                        <div>
                                                            <h4 class="current_time"></h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-md-6 col-xl-3">
                                                <div class="card widget-card-1">
                                                    <div class="card-block-small">
                                                        <i class="icofont icofont-compass-alt bg-c-green card1-icon"></i>
                                                        <span class="text-c-green f-w-600">LAT / LON</span>
                                                        <div>
                                                            <h4 class="current_loc"></h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-12 col-xl-6">
                                                <div class="card">
                                                    <div class="card-block">
                                                        <div>
                                                            <h5>Realtime Heart Rate Data</h5>
                                                            <script src="https://d3js.org/d3.v4.min.js"></script>
                                                            <div width="550" height="405" class="graph"></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-xl-6">
                                                <div class="card">
                                                    <div class="card-block">
                                                        <h5>Current Location</h5>
                                                        <div id="currentMap" class="set-map"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page body end -->
                            </div>
                        </div>
                        <!-- Main-body end -->


                    </div>
                </div>
            </div>
        </div>
        <div class="fixed-button">
            <a href="#homeup" id="homeup" class="btn btn-md btn-primary">
                Top
            </a>
        </div>
    </div>

    <script>

    </script>

    <!-- Warning Section Starts -->
    <!-- Older IE warning message -->
    <!-- Warning Section Ends -->
    <!-- Required Jquery -->
    <script type="text/javascript" src="js/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="js/popper.js/popper.min.js"></script>
    <script type="text/javascript" src="js/bootstrap/js/bootstrap.min.js"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="js/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- modernizr js -->
    <script type="text/javascript" src="js/modernizr/modernizr.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script type="text/javascript " src="js/SmoothScroll.js"></script>
    <script src="js/pcoded.min.js"></script>
    <script src="js/demo-12.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript" src="/js/timezone-js/src/date.js"></script>

    <script>
        var user_id = <?php echo $user['user_id']?>;

        var $window = $(window);
        var nav = $('.fixed-button');
        $window.scroll(function(){
            if ($window.scrollTop() >= 200) {
                nav.addClass('active');
            }
            else {
                nav.removeClass('active');
            }
        });

        setInterval(function() {
            $.ajax({
                type: "get",
                url: "/api/users/<?echo $user['user_id'] ?>/hrdata?limit=1&orderby=true",
                dataType: "json",
                success: function (msg) {
                    var recentJSonData = msg.data.hrdata[0];
                    if (recentJSonData == undefined)
                        return;

                    var nowTime = moment.parseZone(moment.tz(new Date(), "America/Los_Angeles").format());
                    var dataTime = moment.parseZone(moment.tz(recentJSonData.hrdata_timestamp, "America/Los_Angeles").format());

                    if ((nowTime.valueOf() - 5000) < dataTime.valueOf()) {
                        if(!$('.hr_chart').is(':visible')) {
                            $('.hr_chart').show();
                            $('.error-msg').hide();

                            $.ajax({
                                url: "/js/realtimehr.js",
                                dataType: "script"
                            });
                        }
                    }
                },
            });
        }, 5000);

        $(document).ready(function() {
            $('#homeup').click(function(){
                $('body,html').animate({
                    scrollTop : 0
                }, 800);
                return false;
            });

            $.ajax({
                type: "get",
                url: "/api/users/<?echo $user['user_id'] ?>/hrdata?limit=1&orderby=true",
                dataType: "json",
                success: function (msg) {
                    var recentJSonData = msg.data.hrdata[0];
                    if (recentJSonData == undefined)
                        return;

                    var nowTime = moment.parseZone(moment.tz(new Date(), "America/Los_Angeles").format());
                    var dataTime = moment.parseZone(moment.tz(recentJSonData.hrdata_timestamp, "America/Los_Angeles").format());

                    if ((nowTime.valueOf() - 5000) < dataTime.valueOf()) {
                        $('.hr_chart').show();
                        $('.error-msg').hide();

                        $.ajax({
                            url: "/js/realtimehr.js",
                            dataType: "script"
                        });
                    } else {
                        $('.hr_chart').hide();
                        $('.error-msg').show();
                    }
                },
            });
        });
    </script>
</body>

</html>
