<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $title ?></title>
    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- Favicon icon -->
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="/icon/themify-icons/themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="/icon/icofont/css/icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.mCustomScrollbar.css">

    <script src="https://d3js.org/d3.v4.min.js"></script>
</head>

<body>
<div id="pcoded" class="pcoded">
    <div class="pcoded-container navbar-wrapper">
        <nav class="navbar header-navbar pcoded-header">
            <div class="navbar-wrapper">

                <div class="navbar-logo">
                    <a class="mobile-menu" id="mobile-collapse" target="_self" style="color: #000000; cursor: pointer;">
                        <i class="ti-menu"></i>
                    </a>
                    <a href="/">
                        <img class="img-fluid" src="/img/logo/logo.png" width="120" height="30" alt="Theme-Logo"/>
                    </a>
                    <a class="mobile-options">
                        <i class="ti-more"></i>
                    </a>
                </div>

                <div class="navbar-container container-fluid">
                    <ul class="nav-right">
                        <li>
                            <form id="signout" action="/signout" method="post">
                                <input type="hidden" name="csrf-token" value="<?php echo $_SESSION['csrf-token'] ?>"/>
                            </form>

                            <a href="#" onclick="$('#signout').submit(); return false">
                                <i class="ti-layout-sidebar-left"></i> Signout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="pcoded-main-container">
            <div class="pcoded-wrapper">
                <nav class="pcoded-navbar">
                    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
                    <div class="pcoded-inner-navbar main-menu">
                        <div class="">
                            <div class="main-menu-header">
                                <div class="user-details">
                                    <span id="more-details"><?php echo $user['fname'] . ' ' . $user['lname'] ?><i
                                                class="ti-angle-down"></i></span>
                                </div>
                            </div>

                            <div class="main-menu-content">
                                <ul>
                                    <li class="more-details">
                                        <a href="/profile"><i class="ti-user"></i>Profile</a>
                                        <a href="/boards"><i class="ti-tablet"></i>Boards</a>
                                        <a href="#" onclick="$('#signout').submit(); return false">
                                            <i class="ti-layout-sidebar-left"></i>Signout
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="pcoded-navigatio-lavel">Home</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li class="active">
                                <a href="/">
                                    <span class="pcoded-micon"><i class="ti-home"></i></span>
                                    <span class="pcoded-mtext">Dashboard</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">Air Quality Index</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/aqimaps">
                                    <span class="pcoded-micon"><i class="ti-map-alt"></i></span>
                                    <span class="pcoded-mtext">Real-time AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>

                            <li>
                                <a href="/historyaqi">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Historical AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">User Air Pollution</div>
                        <?php if (count($boards) > 0) {
                            for ($i = 0; $i < count($boards); ++$i) { ?>
                                <ul class="pcoded-item pcoded-left-item">
                                    <li class="pcoded-hasmenu">
                                        <a href="javascript:void(0)">
                                            <span class="pcoded-micon"><i class="ti-tablet"></i></span>
                                            <span class="pcoded-mtext"><?php echo $boards[$i]['name'] ?></span>
                                            <span class="pcoded-mcaret"></span>
                                        </a>
                                        <ul class="pcoded-submenu">
                                            <li>
                                                <a href="/realtimeap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Real-Time Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/historyap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                                    <span class="pcoded-mtext">Historical Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/paqichart/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Historical AQI Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            <?php }
                        } else { ?>
                            <ul class="pcoded-item pcoded-left-item">
                                <li>
                                    <a>
                                        <span style="width: 30px; display: inline-block;"></span>
                                        <span class="pcoded-mtext">No Boards</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li>
                            </ul>
                        <?php } ?>

                        <div class="pcoded-navigatio-lavel">User Healthcare information</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/realtimehr">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Real-Time Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                            <li>
                                <a href="/historyhr">
                                    <span class="pcoded-micon"><i class="ti-archive"></i></span>
                                    <span class="pcoded-mtext">Historical Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="pcoded-content">
                    <div class="pcoded-inner-content">
                        <!-- Main-body start -->
                        <div class="main-body">
                            <div class="page-wrapper">
                                <div class="page-body">
                                    <div class="row">
                                        <div class="col-md-12 col-xl-6">
                                            <div class="card fb-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-energy-air"></i>
                                                    <div class="d-inline-block">
                                                        <h4 style="color: #fff">PM 2.5</h4>
                                                        <span>Latest PM 2.5 Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-6 b-r-default">
                                                            <h2 class="pm25_aqi">-</h2>
                                                            <p class="text-muted">Air Quality Index</p>
                                                        </div>
                                                        <div class="col-6">
                                                            <h2 class="pm25_ap">-</h2>
                                                            <p class="text-muted">µg/m^3</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12 col-xl-6">
                                            <div class="card dribble-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-pulse"></i>
                                                    <div class="d-inline-block">
                                                        <h4 style="color: #fff">Heart Rate</h4>
                                                        <span>Latest Heart Rate Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <h2 class="hr">-</h2>
                                                            <p class="text-muted">BPM</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12 col-xl-3">
                                            <div class="card fb-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-energy-air"></i>
                                                    <div class="d-inline-block">
                                                        <h5>CO</h5>
                                                        <span>Latest CO Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-6 b-r-default">
                                                            <h2 class="co_aqi">-</h2>
                                                            <p class="text-muted">AQI</p>
                                                        </div>
                                                        <div class="col-6">
                                                            <h2 class="co_ap">-</h2>
                                                            <p class="text-muted">ppm</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12 col-xl-3">
                                            <div class="card fb-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-energy-air"></i>
                                                    <div class="d-inline-block">
                                                        <h5>O3</h5>
                                                        <span>Latest O3 Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-6 b-r-default">
                                                            <h2 class="o3_aqi">-</h2>
                                                            <p class="text-muted">AQI</p>
                                                        </div>
                                                        <div class="col-6">
                                                            <h2 class="o3_ap">-</h2>
                                                            <p class="text-muted">ppb</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12 col-xl-6">
                                            <div class="card dribble-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-pulse"></i>
                                                    <div class="d-inline-block">
                                                        <h5>RR Interval</h5>
                                                        <span>Latest RR Interval Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-12">
                                                            <h2 class="rri">-</h2>
                                                            <p class="text-muted">ms</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12 col-xl-3">
                                            <div class="card fb-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-energy-air"></i>
                                                    <div class="d-inline-block">
                                                        <h5>NO2</h5>
                                                        <span>Latest NO Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-6 b-r-default">
                                                            <h2 class="no2_aqi">-</h2>
                                                            <p class="text-muted">AQI</p>
                                                        </div>
                                                        <div class="col-6">
                                                            <h2 class="no2_ap">-</h2>
                                                            <p class="text-muted">ppb</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12 col-xl-3">
                                            <div class="card fb-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-energy-air"></i>
                                                    <div class="d-inline-block">
                                                        <h5>SO2</h5>
                                                        <span>Latest SO2 Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-6 b-r-default">
                                                            <h2 class="so2_aqi">-</h2>
                                                            <p class="text-muted">AQI</p>
                                                        </div>
                                                        <div class="col-6">
                                                            <h2 class="so2_ap">-</h2>
                                                            <p class="text-muted">ppb</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12 col-xl-6">
                                            <div class="card dribble-card">
                                                <div class="card-header">
                                                    <i class="icofont icofont-thermometer"></i>
                                                    <div class="d-inline-block">
                                                        <h5>Temperature</h5>
                                                        <span>Latest Temperature Information</span>
                                                    </div>
                                                </div>
                                                <div class="card-block text-center">
                                                    <div class="row">
                                                        <div class="col-6 b-r-default">
                                                            <h2 class="temp_f">-</h2>
                                                            <p class="text-muted">Fahrenheit (℉)</p>
                                                        </div>
                                                        <div class="col-6">
                                                            <h2 class="temp_c">-</h2>
                                                            <p class="text-muted">Celcius (℃)</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="fixed-button">
            <a href="#homeup" id="homeup" class="btn btn-md btn-primary">
                Top
            </a>
        </div>
    </div>

    <!-- Warning Section Starts -->
    <!-- Older IE warning message -->
    <!-- Warning Section Ends -->
    <!-- Required Jquery -->
    <script type="text/javascript" src="/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/popper.js/popper.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap/js/bootstrap.min.js"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="/js/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- modernizr js -->
    <script type="text/javascript" src="/js/modernizr/modernizr.js"></script>

    <script type="text/javascript" src="/js/script.js"></script>
    <script type="text/javascript " src="/js/SmoothScroll.js"></script>
    <script src="/js/pcoded.min.js"></script>
    <script src="/js/demo-12.js"></script>
    <script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
        var $window = $(window);
        var nav = $('.fixed-button');
        $window.scroll(function () {
            if ($window.scrollTop() >= 200) {
                nav.addClass('active');
            }
            else {
                nav.removeClass('active');
            }
        });

        $(document).ready(function () {
            $('#homeup').click(function () {
                $('body,html').animate({
                    scrollTop: 0
                }, 800);
                return false;
            });

            updateDashBoard();
        });

        function updateDashBoard() {
            d3.csv("/api/users/<?php echo $user['user_id'] ?>/boards/aqidata?csv=true&orderby=true&limit=1", function (d) {
                d.no2 = +d.no2;
                d.o3 = +d.o3;
                d.co = +d.co;
                d.so2 = +d.so2;
                d.pm25 = +d.pm25;
                d.lat = +d.lat;
                d.lng = +d.lng;
                return d;
            }, function (err, data) {
                if (err)
                    throw err;

                if (typeof data[0] != "undefined") {
                    d3.select(".pm25_aqi").html(data[0].pm25);
                    d3.select(".co_aqi").html(data[0].co);
                    d3.select(".o3_aqi").html(data[0].o3);
                    d3.select(".no2_aqi").html(data[0].no2);
                    d3.select(".so2_aqi").html(data[0].so2);
                }
            });

            d3.csv("/api/users/<?php echo $user['user_id'] ?>/boards/apdata?csv=true&orderby=true&limit=1", function (d) {
                d.no2 = +d.no2;
                d.o3 = +d.o3;
                d.co = +d.co;
                d.so2 = +d.so2;
                d.pm25 = +d.pm25;
                d.temp = +d.temp;
                d.temp_c = ((d.temp - 32)*5/9).toFixed(3);
                d.lat = +d.lat;
                d.lng = +d.lng;
                return d;
            }, function (err, data) {
                if (err)
                    throw err;

                if (typeof data[0] != "undefined") {
                    d3.select(".pm25_ap").html(data[0].pm25);
                    d3.select(".co_ap").html(data[0].co.toFixed(1));
                    d3.select(".o3_ap").html(data[0].o3.toFixed(1));
                    d3.select(".no2_ap").html(data[0].no2.toFixed(1));
                    d3.select(".so2_ap").html(data[0].so2.toFixed(1));

                    d3.select(".temp_f").html(data[0].temp);
                    d3.select(".temp_c").html(data[0].temp_c);
                }
            });

            d3.csv("/api/users/<?php echo $user['user_id'] ?>/hrdata?csv=true&limit=1&orderby=true", function (d) {
                d.hr = +d.hr;
                d.rri = +d.rri;
                return d;
            }, function (err, data) {
                if (err)
                    throw err;

                if (typeof data[0] != "undefined") {
                    d3.select(".hr").html(data[0].hr);
                    d3.select(".rri").html(data[0].rri);
                }
            });
        }

        setInterval(function() {
            updateDashBoard();
        }, 1000);
    </script>
</body>

</html>
