<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $title ?></title>
    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- Favicon icon -->
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="/icon/themify-icons/themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="/icon/icofont/css/icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.mCustomScrollbar.css">

    <script type="text/javascript" src="/js/jquery/jquery.min.js"></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>

    <style>
        .line {
            clip-path: url(#clip);
        }

        .zoom {
            cursor: move;
            fill: none;
            pointer-events: all;
        }
    </style>
</head>

<body>
<div id="pcoded" class="pcoded">
    <div class="pcoded-container navbar-wrapper">
        <nav class="navbar header-navbar pcoded-header">
            <div class="navbar-wrapper">

                <div class="navbar-logo">
                    <a class="mobile-menu" id="mobile-collapse" target="_self" style="color: #000000; cursor: pointer;">
                        <i class="ti-menu"></i>
                    </a>
                    <a href="/">
                        <img class="img-fluid" src="/img/logo/logo.png" width="120" height="30" alt="Theme-Logo"/>
                    </a>
                    <a class="mobile-options">
                        <i class="ti-more"></i>
                    </a>
                </div>

                <div class="navbar-container container-fluid">
                    <ul class="nav-right">
                        <li>
                            <form id="signout" action="/signout" method="post">
                                <input type="hidden" name="csrf-token" value="<?php echo $_SESSION['csrf-token'] ?>"/>
                            </form>

                            <a href="#" onclick="$('#signout').submit(); return false">
                                <i class="ti-layout-sidebar-left"></i> Signout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="pcoded-main-container">
            <div class="pcoded-wrapper">
                <nav class="pcoded-navbar">
                    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
                    <div class="pcoded-inner-navbar main-menu">
                        <div class="">
                            <div class="main-menu-header">
                                <div class="user-details">
                                    <span id="more-details"><?php echo $user['fname'] . ' ' . $user['lname'] ?><i
                                                class="ti-angle-down"></i></span>
                                </div>
                            </div>

                            <div class="main-menu-content">
                                <ul>
                                    <li class="more-details">
                                        <a href="/profile"><i class="ti-user"></i>Profile</a>
                                        <a href="/boards"><i class="ti-tablet"></i>Boards</a>
                                        <a href="#" onclick="$('#signout').submit(); return false">
                                            <i class="ti-layout-sidebar-left"></i>Signout
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="pcoded-navigatio-lavel">Home</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li class="active">
                                <a href="/">
                                    <span class="pcoded-micon"><i class="ti-home"></i></span>
                                    <span class="pcoded-mtext">Dashboard</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">Air Quality Index</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/aqimaps">
                                    <span class="pcoded-micon"><i class="ti-map-alt"></i></span>
                                    <span class="pcoded-mtext">Real-time AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>

                            <li>
                                <a href="/historyaqi">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Historical AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">User Air Pollution</div>
                        <?php if (count($boards) > 0) {
                            for ($i = 0; $i < count($boards); ++$i) { ?>
                                <ul class="pcoded-item pcoded-left-item">
                                    <li class="pcoded-hasmenu">
                                        <a href="javascript:void(0)">
                                            <span class="pcoded-micon"><i class="ti-tablet"></i></span>
                                            <span class="pcoded-mtext"><?php echo $boards[$i]['name'] ?></span>
                                            <span class="pcoded-mcaret"></span>
                                        </a>
                                        <ul class="pcoded-submenu">
                                            <li>
                                                <a href="/realtimeap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Real-Time Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/historyap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                                    <span class="pcoded-mtext">Historical Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/paqichart/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Historical AQI Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            <?php }
                        } else { ?>
                            <ul class="pcoded-item pcoded-left-item">
                                <li>
                                    <a>
                                        <span style="width: 30px; display: inline-block;"></span>
                                        <span class="pcoded-mtext">No Boards</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li>
                            </ul>
                        <?php } ?>

                        <div class="pcoded-navigatio-lavel">User Healthcare information</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/realtimehr">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Real-Time Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                            <li>
                                <a href="/historyhr">
                                    <span class="pcoded-micon"><i class="ti-archive"></i></span>
                                    <span class="pcoded-mtext">Historical Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="pcoded-content">
                    <div class="pcoded-inner-content">
                        <!-- Main-body start -->
                        <div class="main-body">
                            <div class="page-wrapper">
                                <!-- Page-header start -->
                                <div class="page-header card">
                                    <div class="row align-items-end">
                                        <div class="col-lg-8">
                                            <div class="page-header-title">
                                                <i class="icofont icofont-chart-histogram bg-c-pink"></i>
                                                <div class="d-inline">
                                                    <h4>Historical Air Pollution Charts</h4>
                                                    <span>public historical charts</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="page-header-breadcrumb">
                                                <ul class="breadcrumb-title">
                                                    <li class="breadcrumb-item">
                                                        <a href="/">
                                                            <i class="icofont icofont-home"></i>
                                                        </a>
                                                    </li>
                                                    <li class="breadcrumb-item"><a href="/historyap">Historical Charts</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page-header end -->

                                <!-- Page body start -->
                                <div class="page-body">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="card">
                                                <div class="card-block">
                                                    <div id="morris-extra-area">
                                                        <select id="inds">
                                                            <option value="no2" selected="selected">NO2</option>
                                                            <option value="o3">O3</option>
                                                            <option value="co">CO</option>
                                                            <option value="so2">SO2</option>
                                                            <option value="pm25">PM2.5</option>
                                                            <option value="temp">Temperature (℉)</option>
                                                        </select>
                                                        <svg width="1100" height="500"></svg>
                                                        <script src="https://d3js.org/d3.v4.min.js"></script>
                                                        <script>
                                                            var svg = d3.select("svg"),
                                                                margin = {top: 20, right: 20, bottom: 110, left: 40},
                                                                margin2 = {top: 430, right: 20, bottom: 30, left: 40},
                                                                width = +svg.attr("width") - margin.left - margin.right,
                                                                height = +svg.attr("height") - margin.top - margin.bottom,
                                                                height2 = +svg.attr("height") - margin2.top - margin2.bottom;

                                                            var parseDate = d3.timeParse("%b %Y");

                                                            var x = d3.scaleTime().range([0, width]),
                                                                x2 = d3.scaleTime().range([0, width]),
                                                                y = d3.scaleLinear().range([height, 0]),
                                                                y2 = d3.scaleLinear().range([height2, 0]);

                                                            var xAxis = d3.axisBottom(x),
                                                                xAxis2 = d3.axisBottom(x2),
                                                                yAxis = d3.axisLeft(y);

                                                            var brush = d3.brushX()
                                                                .extent([[0, 0], [width, height2]])
                                                                .on("brush end", brushed);

                                                            var zoom = d3.zoom()
                                                                .scaleExtent([1, Infinity])
                                                                .translateExtent([[0, 0], [width, height]])
                                                                .extent([[0, 0], [width, height]])
                                                                .on("zoom", zoomed);

                                                            var line = d3.line()
                                                                .curve(d3.curveLinear)
                                                                .x(function(d) { return x(d.date); })
                                                                .y(function(d) { return y(d.value); });

                                                            var line2 = d3.line()
                                                                .curve(d3.curveLinear)
                                                                .x(function(d) { return x2(d.date); })
                                                                .y(function(d) { return y2(d.value); });

                                                            svg.append("defs").append("clipPath")
                                                                .attr("id", "clip")
                                                                .append("rect")
                                                                .attr("width", width)
                                                                .attr("height", height);

                                                            var focus = svg.append("g")
                                                                .attr("class", "focus")
                                                                .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

                                                            var context = svg.append("g")
                                                                .attr("class", "context")
                                                                .attr("transform", "translate(" + margin2.left + "," + margin2.top + ")");

                                                            d3.csv("/api/users/<?php echo $user['user_id'] ?>/boards/apdata?csv=true&orderby=true", type, function(error, data) {
                                                                if (error) throw error;
                                                                d3.select('#inds')
                                                                    .on("change", function() {
                                                                        var sect = document.getElementById("inds");
                                                                        var section = sect.options[sect.selectedIndex].value;

                                                                        data.forEach(function(d) {
                                                                            d.value = +d[section];
                                                                        });

                                                                        updateData(data, sect.options[sect.selectedIndex].text);
                                                                    });

                                                                updateData(data, document.getElementById("inds").options[0].text);
                                                            });

                                                            function updateData(data, text) {
                                                                d3.selectAll(".tick").remove();
                                                                d3.selectAll("text").remove();
                                                                d3.selectAll("path.line").remove();
                                                                d3.selectAll(".brush").remove();
                                                                d3.selectAll("rect.zoom").remove();
                                                                d3.selectAll(".axis").remove();

                                                                x.domain(d3.extent(data, function(d) { return d.date; }));
                                                                y.domain([0, d3.max(data, function(d) { return d.value; })]);
                                                                x2.domain(x.domain());
                                                                y2.domain(y.domain());

                                                                focus.append("g")
                                                                    .call(d3.axisLeft(y))
                                                                    .append("text")
                                                                    .attr("fill", "#000")
                                                                    .attr("transform", "rotate(-90)")
                                                                    .attr("y", 6)
                                                                    .attr("dy", "1em")
                                                                    .attr("text-anchor", "end")
                                                                    .attr('font-size', "12px")
                                                                    .text(text);

                                                                focus.append("path")
                                                                    .datum(data)
                                                                    .attr("class", "line")
                                                                    .attr("fill", "none")
                                                                    .attr("stroke", "steelblue")
                                                                    .attr("stroke-linejoin", "round")
                                                                    .attr("stroke-linecap", "round")
                                                                    .attr("stroke-width", 1)
                                                                    .attr("d", line);

                                                                focus.append("g")
                                                                    .attr("class", "axis axis--x")
                                                                    .attr("transform", "translate(0," + height + ")")
                                                                    .call(xAxis);

                                                                focus.append("g")
                                                                    .attr("class", "axis axis--y")
                                                                    .call(yAxis);

                                                                context.append("path")
                                                                    .datum(data)
                                                                    .attr("class", "line")
                                                                    .attr("fill", "none")
                                                                    .attr("stroke", "steelblue")
                                                                    .attr("stroke-linejoin", "round")
                                                                    .attr("stroke-linecap", "round")
                                                                    .attr("stroke-width", 1)
                                                                    .attr("d", line2);

                                                                context.append("g")
                                                                    .attr("class", "axis axis--x")
                                                                    .attr("transform", "translate(0," + height2 + ")")
                                                                    .call(xAxis2);

                                                                context.append("g")
                                                                    .attr("class", "brush")
                                                                    .call(brush)
                                                                    .call(brush.move, x.range());

                                                                svg.append("rect")
                                                                    .attr("class", "zoom")
                                                                    .attr("width", width)
                                                                    .attr("height", height)
                                                                    .attr("transform", "translate(" + margin.left + "," + margin.top + ")")
                                                                    .call(zoom);
                                                            }

                                                            function brushed() {
                                                                if (d3.event.sourceEvent && d3.event.sourceEvent.type === "zoom") return; // ignore brush-by-zoom
                                                                var s = d3.event.selection || x2.range();
                                                                x.domain(s.map(x2.invert, x2));
                                                                focus.select(".line").attr("d", line);
                                                                focus.select(".axis--x").call(xAxis);
                                                                svg.select(".zoom").call(zoom.transform, d3.zoomIdentity
                                                                    .scale(width / (s[1] - s[0]))
                                                                    .translate(-s[0], 0));
                                                            }

                                                            function zoomed() {
                                                                if (d3.event.sourceEvent && d3.event.sourceEvent.type === "brush") return; // ignore zoom-by-brush
                                                                var t = d3.event.transform;
                                                                x.domain(t.rescaleX(x2).domain());
                                                                focus.select(".line").attr("d", line);
                                                                focus.select(".axis--x").call(xAxis);
                                                                context.select(".brush").call(brush.move, x.range().map(t.invertX, t));
                                                            }

                                                            function type(d) {
                                                                d.date = new Date(d.timestamp);
                                                                d.value = +d.no2;
                                                                d.no2 = +d.no2;
                                                                d.o3 = +d.o3;
                                                                d.co = +d.co;
                                                                d.so2 = +d.so2;
                                                                d.pm10 = +d.pm10;
                                                                d.pm25 = +d.pm25;
                                                                d.temp = +d.temp;
                                                                d.lat = +d.lat;
                                                                d.lng = +d.lng;
                                                                d.timestamp = new Date(d.timestamp);
                                                                return d;
                                                            }

                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page body end -->
                            </div>
                        </div>
                        <!-- Main-body end -->


                    </div>
                </div>
            </div>
        </div>
        <div class="fixed-button">
            <a href="#homeup" id="homeup" class="btn btn-md btn-primary">
                Top
            </a>
        </div>
    </div>

    <!-- Warning Section Starts -->
    <!-- Older IE warning message -->
    <!-- Warning Section Ends -->
    <!-- Required Jquery -->
    <script type="text/javascript" src="/js/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/popper.js/popper.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap/js/bootstrap.min.js"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="/js/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- modernizr js -->
    <script type="text/javascript" src="/js/modernizr/modernizr.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
    <script type="text/javascript " src="/js/SmoothScroll.js"></script>
    <script src="/js/pcoded.min.js"></script>
    <script src="/js/demo-12.js"></script>
    <script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
        var $window = $(window);
        var nav = $('.fixed-button');
        $window.scroll(function(){
            if ($window.scrollTop() >= 200) {
                nav.addClass('active');
            }
            else {
                nav.removeClass('active');
            }
        });

        $(document).ready(function() {
            $('#homeup').click(function(){
                $('body,html').animate({
                    scrollTop : 0
                }, 800);
                return false;
            });
        });
    </script>
</body>

</html>
