<!DOCTYPE html>
<html lang="en">

<head>
    <title> <?php echo $title ?> </title>
    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- Favicon icon -->
    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="/css/bootstrap/bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="/icon/themify-icons/themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="/icon/icofont/css/icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.mCustomScrollbar.css">

    <script type="text/javascript" src="/js/jquery/jquery.min.js"></script>


    <script type="text/javascript" src="/js/timezone/moment.min.js"></script>
    <script type="text/javascript" src="/js/timezone/moment-timezone.js"></script>

    <style>
        .axis text {
            font: 10px sans-serif;
        }
        .chartTitle {
            font-size: 12px;
            font-weight: bold;
            text-anchor: middle;
        }
        .axis .title {
            font-weight: bold;
            text-anchor: middle;
        }
        .axis path,
        .axis line {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
        .x.axis path {
            fill: none;
            stroke: #000;
            shape-rendering: crispEdges;
        }
        .nav .area {
            fill: lightgrey;
            stroke-width: 0px;
        }
        .nav .line {
            fill: none;
            stroke: darkgrey;
            stroke-width: 1px;
        }
        .viewport {
            stroke: grey;
            fill: black;
            fill-opacity: 0.3;
        }
        .viewport .extent {
            fill: green;
        }
        .well {
            padding-top: 0px;
            padding-bottom: 0px;
        }
    </style>
</head>

<body>
<div id="pcoded" class="pcoded">
    <div class="pcoded-container navbar-wrapper">
        <nav class="navbar header-navbar pcoded-header">
            <div class="navbar-wrapper">

                <div class="navbar-logo">
                    <a class="mobile-menu" id="mobile-collapse" target="_self" style="color: #000000; cursor: pointer;">
                        <i class="ti-menu"></i>
                    </a>
                    <a href="/">
                        <img class="img-fluid" src="/img/logo/logo.png" width="120" height="30" alt="Theme-Logo"/>
                    </a>
                    <a class="mobile-options">
                        <i class="ti-more"></i>
                    </a>
                </div>

                <div class="navbar-container container-fluid">
                    <ul class="nav-right">
                        <li>
                            <form id="signout" action="/signout" method="post">
                                <input type="hidden" name="csrf-token" value="<?php echo $_SESSION['csrf-token'] ?>"/>
                            </form>

                            <a href="#" onclick="$('#signout').submit(); return false">
                                <i class="ti-layout-sidebar-left"></i> Signout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="pcoded-main-container">
            <div class="pcoded-wrapper">
                <nav class="pcoded-navbar">
                    <div class="sidebar_toggle"><a href="#"><i class="icon-close icons"></i></a></div>
                    <div class="pcoded-inner-navbar main-menu">
                        <div class="">
                            <div class="main-menu-header">
                                <div class="user-details">
                                    <span id="more-details"><?php echo $user['fname'] . ' ' . $user['lname'] ?><i
                                                class="ti-angle-down"></i></span>
                                </div>
                            </div>

                            <div class="main-menu-content">
                                <ul>
                                    <li class="more-details">
                                        <a href="/profile"><i class="ti-user"></i>Profile</a>
                                        <a href="/boards"><i class="ti-tablet"></i>Boards</a>
                                        <a href="#" onclick="$('#signout').submit(); return false">
                                            <i class="ti-layout-sidebar-left"></i>Signout
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="pcoded-navigatio-lavel">Home</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li class="active">
                                <a href="/">
                                    <span class="pcoded-micon"><i class="ti-home"></i></span>
                                    <span class="pcoded-mtext">Dashboard</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">Air Quality Index</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/aqimaps">
                                    <span class="pcoded-micon"><i class="ti-map-alt"></i></span>
                                    <span class="pcoded-mtext">Real-time AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>

                            <li>
                                <a href="/historyaqi">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Historical AQI Map</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>

                        <div class="pcoded-navigatio-lavel">User Air Pollution</div>
                        <?php if (count($boards) > 0) {
                            for ($i = 0; $i < count($boards); ++$i) { ?>
                                <ul class="pcoded-item pcoded-left-item">
                                    <li class="pcoded-hasmenu">
                                        <a href="javascript:void(0)">
                                            <span class="pcoded-micon"><i class="ti-tablet"></i></span>
                                            <span class="pcoded-mtext"><?php echo $boards[$i]['name'] ?></span>
                                            <span class="pcoded-mcaret"></span>
                                        </a>
                                        <ul class="pcoded-submenu">
                                            <li>
                                                <a href="/realtimeap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Real-Time Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/historyap/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                                    <span class="pcoded-mtext">Historical Air Pollution Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/paqichart/<?php echo $boards[$i]['board_id'] ?>">
                                                    <span class="pcoded-micon"><i class="ti-angle-right"></i></span>
                                                    <span class="pcoded-mtext">Historical AQI Chart</span>
                                                    <span class="pcoded-mcaret"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            <?php }
                        } else { ?>
                            <ul class="pcoded-item pcoded-left-item">
                                <li>
                                    <a>
                                        <span style="width: 30px; display: inline-block;"></span>
                                        <span class="pcoded-mtext">No Boards</span>
                                        <span class="pcoded-mcaret"></span>
                                    </a>
                                </li>
                            </ul>
                        <?php } ?>

                        <div class="pcoded-navigatio-lavel">User Healthcare information</div>
                        <ul class="pcoded-item pcoded-left-item">
                            <li>
                                <a href="/realtimehr">
                                    <span class="pcoded-micon"><i class="ti-bar-chart"></i></span>
                                    <span class="pcoded-mtext">Real-Time Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                            <li>
                                <a href="/historyhr">
                                    <span class="pcoded-micon"><i class="ti-archive"></i></span>
                                    <span class="pcoded-mtext">Historical Heart Rate</span>
                                    <span class="pcoded-mcaret"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="pcoded-content">
                    <div class="pcoded-inner-content">
                        <!-- Main-body start -->
                        <div class="main-body">
                            <div class="page-wrapper">
                                <!-- Page-header start -->
                                <div class="page-header card">
                                    <div class="row align-items-end">
                                        <div class="col-lg-8">
                                            <div class="page-header-title">
                                                <i class="icofont icofont-chart-histogram bg-c-pink"></i>
                                                <div class="d-inline">
                                                    <h4>Real Time Air Pollution Data</h4>
                                                    <span><?php echo $user['fname']?>'s Collected Air Pollution Data</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="page-header-breadcrumb">
                                                <ul class="breadcrumb-title">
                                                    <li class="breadcrumb-item">
                                                        <a href="/">
                                                            <i class="icofont icofont-home"></i>
                                                        </a>
                                                    </li>
                                                    <li class="breadcrumb-item"><a href="/realtimeap/<?php echo $selectedBid ?>">Real Time AP</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page-header end -->



                                <!-- Page body start -->
                                <div class="page-body">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="card">
                                                <div class="card-block">
                                                    <div id="view_pm25"></div>
                                                    <div id="view_co"></div>
                                                    <div id="view_o3"></div>
                                                    <div id="view_no2"></div>
                                                    <div id="view_so2"></div>
                                                    <div id="view_temp"></div>
                                                    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
                                                    <script src="/js/realTimeChart.js"></script>
                                                    <script>
                                                        'use strict';

                                                        // mean and deviation for time interval
                                                        var meanMs = 1000, // milliseconds
                                                            dev = 150;

                                                        // define time scale
                                                        var timeScale = d3.scale.linear()
                                                            .domain([300, 1700])
                                                            .range([300, 1700])
                                                            .clamp(true);

                                                        // define value scale
                                                        var valueScale = d3.scale.linear()
                                                            .domain([0, 1])
                                                            .range([30, 95]);

                                                        // create the real time chart
                                                        var chart = realTimeChart()
                                                            .title("Real Time PM 2.5")
                                                            .yTitle("PM2.5 (µg/m^3)")
                                                            .xTitle("Time")
                                                            .border(true)
                                                            .width(1100)
                                                            .height(550)
                                                            .barWidth(1);

                                                        // invoke the chart
                                                        var chartDiv = d3.select("#view_pm25").append("div")
                                                            .attr("id", "chartDiv")
                                                            .call(chart);

                                                        var chart_co = realTimeChart()
                                                            .title("Real Time CO")
                                                            .yTitle("CO (ppm)")
                                                            .xTitle("Time")
                                                            .border(true)
                                                            .width(1100)
                                                            .height(550)
                                                            .barWidth(1);

                                                        // invoke the chart
                                                        var chartCoDiv = d3.select("#view_co").append("div")
                                                            .attr("id", "chartDiv")
                                                            .call(chart_co);

                                                        var chart_o3 = realTimeChart()
                                                            .title("Real Time O3")
                                                            .yTitle("O3 (ppb)")
                                                            .xTitle("Time")
                                                            .border(true)
                                                            .width(1100)
                                                            .height(550)
                                                            .barWidth(1);

                                                        // invoke the chart
                                                        var chartO3Div = d3.select("#view_o3").append("div")
                                                            .attr("id", "chartDiv")
                                                            .call(chart_o3);

                                                        var chart_no2 = realTimeChart()
                                                            .title("Real Time NO2")
                                                            .yTitle("NO2 (ppb)")
                                                            .xTitle("Time")
                                                            .border(true)
                                                            .width(1100)
                                                            .height(550)
                                                            .barWidth(1);

                                                        // invoke the chart
                                                        var chartNo2Div = d3.select("#view_no2").append("div")
                                                            .attr("id", "chartDiv")
                                                            .call(chart_no2);

                                                        var chart_so2 = realTimeChart()
                                                            .title("Real Time SO2")
                                                            .yTitle("SO2 (ppb)")
                                                            .xTitle("Time")
                                                            .border(true)
                                                            .width(1100)
                                                            .height(550)
                                                            .barWidth(1);

                                                        // invoke the chart
                                                        var chartSo2Div = d3.select("#view_so2").append("div")
                                                            .attr("id", "chartDiv")
                                                            .call(chart_so2);

                                                        var chart_temp = realTimeChart()
                                                            .title("Real Time Temperature")
                                                            .yTitle("TEMPERATURE (℉)")
                                                            .xTitle("Time")
                                                            .border(true)
                                                            .width(1100)
                                                            .height(550)
                                                            .barWidth(1);

                                                        // invoke the chart
                                                        var chartTempDiv = d3.select("#view_temp").append("div")
                                                            .attr("id", "chartDiv")
                                                            .call(chart_temp);

                                                        var d = 0;
                                                        function dataGenerator() {

                                                            var timeout = 3000;

                                                            setTimeout(function() {
                                                                d3.csv('/api/users/<?php echo $user['user_id'] ?>/boards/<?php echo $selectedBid ?>/apdata?csv=true&limit=1&orderby=true', function(d){
                                                                    d.date = new Date(d.timestamp);
                                                                    d.pm25 = +d.pm25;
                                                                    d.co = +d.co;
                                                                    d.o3 = +d.o3;
                                                                    d.no2 = +d.no2;
                                                                    d.so2 = +d.so2;
                                                                    d.temp = +d.temp;
                                                                    return d;
                                                                }, function(err, data) {
                                                                    var obj_pm25 = {
                                                                        value: data[0]['pm25'], // random data
                                                                        //value: Math.round((d++ % 60) / 60 * 95), // ramp data
                                                                        time: data[0].date,
                                                                        color: "red",
                                                                        ts: data[0].date.getTime(),
                                                                        interval: timeout
                                                                    };

                                                                    chart.datum(obj_pm25);

                                                                    var obj_co = {
                                                                        value: data[0]['co'], // random data
                                                                        //value: Math.round((d++ % 60) / 60 * 95), // ramp data
                                                                        time: data[0].date,
                                                                        color: "red",
                                                                        ts: data[0].date.getTime(),
                                                                        interval: timeout
                                                                    };

                                                                    chart_co.datum(obj_co);

                                                                    var obj_o3 = {
                                                                        value: data[0]['o3'], // random data
                                                                        //value: Math.round((d++ % 60) / 60 * 95), // ramp data
                                                                        time: data[0].date,
                                                                        color: "red",
                                                                        ts: data[0].date.getTime(),
                                                                        interval: timeout
                                                                    };

                                                                    chart_o3.datum(obj_o3);

                                                                    var obj_no2 = {
                                                                        value: data[0]['no2'], // random data
                                                                        //value: Math.round((d++ % 60) / 60 * 95), // ramp data
                                                                        time: data[0].date,
                                                                        color: "red",
                                                                        ts: data[0].date.getTime(),
                                                                        interval: timeout
                                                                    };

                                                                    chart_no2.datum(obj_no2);

                                                                    var obj_so2 = {
                                                                        value: data[0]['so2'], // random data
                                                                        //value: Math.round((d++ % 60) / 60 * 95), // ramp data
                                                                        time: data[0].date,
                                                                        color: "red",
                                                                        ts: data[0].date.getTime(),
                                                                        interval: timeout
                                                                    };

                                                                    chart_so2.datum(obj_so2);

                                                                    var obj_temp = {
                                                                        value: data[0]['temp'], // random data
                                                                        //value: Math.round((d++ % 60) / 60 * 95), // ramp data
                                                                        time: data[0].date,
                                                                        color: "red",
                                                                        ts: data[0].date.getTime(),
                                                                        interval: timeout
                                                                    };

                                                                    chart_temp.datum(obj_temp);

                                                                    // do forever
                                                                    dataGenerator();
                                                                });
                                                            }, timeout);
                                                        }

                                                        // start the data generator
                                                        dataGenerator();
                                                    </script>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Page body end -->
                            </div>
                        </div>
                        <!-- Main-body end -->


                    </div>
                </div>
            </div>
        </div>
        <div class="fixed-button">
            <a href="#homeup" id="homeup" class="btn btn-md btn-primary">
                Top
            </a>
        </div>
    </div>

    <!-- Warning Section Starts -->
    <!-- Older IE warning message -->
    <!-- Warning Section Ends -->
    <!-- Required Jquery -->
    <script type="text/javascript" src="/js/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/popper.js/popper.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap/js/bootstrap.min.js"></script>
    <!-- jquery slimscroll js -->
    <script type="text/javascript" src="/js/jquery-slimscroll/jquery.slimscroll.js"></script>

    <!-- modernizr js -->
    <script type="text/javascript" src="/js/modernizr/modernizr.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
    <script type="text/javascript " src="/js/SmoothScroll.js"></script>
    <script src="/js/pcoded.min.js"></script>
    <script src="/js/demo-12.js"></script>
    <script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script>
        var $window = $(window);
        var nav = $('.fixed-button');
        $window.scroll(function(){
            if ($window.scrollTop() >= 200) {
                nav.addClass('active');
            }
            else {
                nav.removeClass('active');
            }
        });

        $(document).ready(function() {
            $('#homeup').click(function(){
                $('body,html').animate({
                    scrollTop : 0
                }, 800);
                return false;
            });
        });
    </script>
</body>

</html>
