<!DOCTYPE html>
<html>
<head>
    <title><?php echo $title;?></title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <!-- Favicon icon -->
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <!-- Google font-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
    <!-- Required Fremwork -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap/bootstrap.min.css">
    <!-- themify-icons line icon -->
    <link rel="stylesheet" type="text/css" href="icon/themify-icons/themify-icons.css">
    <!-- ico font -->
    <link rel="stylesheet" type="text/css" href="icon/icofont/css/icofont.css">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body class="fix-menu">

<section class="login p-fixed d-flex text-center bg-primary common-img-bg">
    <!-- Container-fluid starts -->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <!-- Authentication card start -->
                <div class="login-card card-block auth-body mr-auto ml-auto">
                    <form class="md-float-material" action="/signin" method="post">
                        <input type="hidden" name="csrf-token" value="<?php echo $_SESSION['csrf-token']?>"/>
                        <div class="text-center">
                            <a href="/">
                                <img src="/img/logo/logo.png" width="170" height="60" alt="logo.png">
                            </a>
                            <!-- <h3 class="text-center txt-primary">SOMI</h3> -->
                        </div>
                        <div class="auth-box">
                            <div class="row m-b-20">
                                <div class="col-md-12">
                                    <h3 class="text-center txt-primary">Sign In</h3>
                                </div>
                            </div>

                            <?php
                                if (isset($_SESSION['slim.flash']['alert'])) {
                                    echo '<div class="alert alert-warning alert-dismissible fade show" role="alert">';
                                    echo '    <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin: 0">';
                                    echo '        <span aria-hidden="true">&times;</span>';
                                    echo '    </button>';
                                    echo '<strong>'.$_SESSION["slim.flash"]["alert"].'</strong>';
                                    echo '</div>';
                                }
                            ?>

                            <div class="input-group">
                                <input type="email" class="form-control" name="email" placeholder="Your Email Address">
                                <span class="md-line"></span>
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="Password" pattern="^.*(?=^.{8,15}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$" oninvalid="this.setCustomValidity('Your password have to contain one digit, alphabet, and special character.')" oninput="setCustomValidity('')">
                                <span class="md-line"></span>
                            </div>
                            <div class="row m-t-25 text-left">
                                <div class="col-sm-12 col-xs-12 forgot-phone text-right">
                                    <a href="/forgotpwd" class="text-right f-w-600 text-inverse">Forgot your password?</a>
                                </div>
                                <div class="col-sm-12 col-xs-12 forgot-phone text-right">
                                    <a href="/signup" class="text-right f-w-600 text-inverse">Sign up here</a>
                                </div>
                            </div>
                            <div class="row m-t-30">
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20">Sign in</button>
                                </div>
                            </div>
                        </div>
                        <div class="text-center" style="margin-top: 10px">
                        <a href="/">
                            <span><img src="/img/logo/somiterm.png" width="450" height="20" alt="logo.png"></span>
                        </a>
                        </div>
                    </form>
                    <!-- end of form -->
                </div>
                <!-- Authentication card end -->
            </div>
            <!-- end of col-sm-12 -->
        </div>
        <!-- end of row -->
    </div>
    <!-- end of container-fluid -->
</section>

<!-- Required Jquery -->
<script type="text/javascript" src="js/jquery/jquery.min.js"></script>
<script type="text/javascript" src="js/jquery-ui/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/popper.js/popper.min.js"></script>
<script type="text/javascript" src="js/bootstrap/js/bootstrap.min.js"></script>
<!-- jquery slimscroll js -->
<script type="text/javascript" src="js/jquery-slimscroll/jquery.slimscroll.js"></script>
<!-- modernizr js -->
<script type="text/javascript" src="js/modernizr/modernizr.js"></script>
<script type="text/javascript" src="js/modernizr/css-scrollbars.js"></script>
<script type="text/javascript" src="js/common-pages.js"></script>

</body>
</html>